### ISSUE TITLE
As a user, I can read articles on my phone offline (progressive web app)

### ISSUE THREAD

**Issue by jeffgore00** [DJA1802/readMe#4]
- [x] #32 Research progressive web app implementation and determine best approach
- [x] #33 Meet to determine PWA implementation subtasks

**Comment by dleistman** [comment]
[Google's Progressive Web App introduction](https://developers.google.com/web/progressive-web-apps/)
[Medium article - Build your first progressive web app with React](https://engineering.musefind.com/build-your-first-progressive-web-app-with-react-8e1449c575cd)
